[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#246BFE"
font = "sans serif"
backgroundColor = "#F4F7FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#17212F"
